<a href="https://colab.research.google.com/github/akashb023/NLP/blob/main/exp10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
!pip install nltk

In [9]:
import numpy as np
import nltk
import re
import spacy
import sklearn
import pickle
from nltk.corpus import stopwords
from sklearn.datasets import load_files
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
review = load_files('/content/drive/MyDrive/review_polarity (1)/txt_sentoken')
x,y = review.data,review.target

In [ ]:
with open('x.pickle','wb') as f:
  pickle.dump(x,f)
  with open('y.pickle','wb') as f:
    pickle.dump(y,f)

In [12]:
corpus=[]
for i in range(len(x)):
  review=re.sub(r'\W',' ',str(x[i]))
  review=review.lower()
  review=re.sub(r'\s+[a-z]\s+','',review)
  review=re.sub(r'^[a-z]\s+','',review)
  review=re.sub(r'\s+',' ',review)
  corpus.append(review)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=2000,max_df=0.6,min_df=2,stop_words=stopwords.words('english'))
x = vectorizer.fit_transform(corpus).toarray()

In [16]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 1, ..., 0, 0, 0]])

In [17]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()
x = transformer.fit_transform(x).toarray()


In [18]:
x

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.12855193, 0.        , 0.06853267, ..., 0.        , 0.        ,
        0.        ]])

In [21]:
from sklearn.model_selection import train_test_split
text_train,text_test,sent_train,sent_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(text_train,sent_train)

LogisticRegression()

In [25]:
sent_pred = classifier.predict(text_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(sent_test, sent_pred)
cm

array([[152,  31],
       [ 38, 182]])